baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

baseURL = "https://manjusredev.github.io/"
languageCode = "en-us"
title = "Manjusredev — DevOps Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[params.social]
  github = "https://github.com/manjusredev"
  linkedin = "https://www.linkedin.com/in/manjunathkm"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "https://github.com/manjusredev"
    weight = 4

[permalinks]
  posts = "/posts/:slug/"

